username: admin
password: admin
port: 57400
timeout: 10s
skip-verify: true
encoding: json_ietf

targets:
  clab-st-leaf1:
  clab-st-leaf2:
  clab-st-leaf3:
  clab-st-spine1:
  clab-st-spine2:

subscriptions:
  srl_if_stats:
    paths:
      - /interface[name=ethernet-1/*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_cpu:
    paths:
      - /platform/control[slot=*]/cpu[index=all]/
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_mem:
    paths:
      - /platform/control[slot=*]/memory
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_bgp_stats:
    paths:
      - /network-instance[name=*]/protocols/bgp/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_ipv4_routes:
    paths:
      - /network-instance[name=*]/route-table/ipv4-unicast/statistics/
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_ipv6_routes:
    paths:
      - /network-instance[name=*]/route-table/ipv6-unicast/statistics/
    mode: stream
    stream-mode: sample
    sample-interval: 5s

outputs:
  prom:
    type: prometheus
    listen: :9273
    path: /metrics
    metric-prefix: gnmic
    append-subscription-name: true
    export-timestamps: true
    debug: false
    event-processors:
      - trim-prefixes
  # stdout:
  #   type: file
  #   file-type: stdout
  #   event-processors:
  #     - proc-convert-strings-to-int
  #     - trim-prefixes

processors:
  trim-prefixes:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - trim-prefix:
            apply-on: "name"
            prefix: "/srl_nokia-interfaces:interface/statistics/"
        - trim-prefix:
            apply-on: "name"
            prefix: "/srl_nokia-platform:platform/srl_nokia-platform-control:control/srl_nokia-platform-cpu:cpu/"
        - trim-prefix:
            apply-on: "name"
            prefix: "/srl_nokia-platform:platform/srl_nokia-platform-control:control/srl_nokia-platform-memory:memory/"
        - trim-prefix:
            apply-on: "name"
            prefix: "/srl_nokia-network-instance:network-instance/protocols/srl_nokia-bgp:bgp/statistics/"
        - trim-prefix:
            apply-on: "name"
            prefix: "/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:ipv4-unicast/statistics/"
        - trim-prefix:
            apply-on: "name"
            prefix: "/srl_nokia-network-instance:network-instance/route-table/srl_nokia-ip-route-tables:ipv6-unicast/statistics/"
