# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

username: admin
password: NokiaSrl1!
port: 57400
timeout: 10s
skip-verify: true
encoding: json_ietf

targets:
  leaf1:
  leaf2:
  leaf3:
  spine1:
  spine2:

subscriptions:
  srl_if_oper_state:
    paths:
      - /interface[name=ethernet-1/*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_net_instance:
    paths:
      - /network-instance[name=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_if_stats:
    paths:
      - /interface[name=ethernet-1/*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_if_traffic_rate:
    paths:
      - /interface[name=ethernet-1/*]/traffic-rate
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_cpu:
    paths:
      - /platform/control[slot=*]/cpu[index=all]/total
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_mem:
    paths:
      - /platform/control[slot=*]/memory
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_bgp_stats:
    paths:
      - /network-instance[name=*]/protocols/bgp/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_ipv4_routes:
    paths:
      - /network-instance[name=*]/route-table/ipv4-unicast/statistics/
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_ipv6_routes:
    paths:
      - /network-instance[name=*]/route-table/ipv6-unicast/statistics/
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  srl_apps:
    paths:
      - /system/app-management/application[name=*]
    mode: stream
    stream-mode: sample
    sample-interval: 5s

outputs:
  prom:
    type: prometheus
    listen: :9273
    path: /metrics
    metric-prefix: gnmic
    append-subscription-name: true
    export-timestamps: true
    debug: false
    event-processors:
      - trim-prefixes
      - up-down-map
  # stdout:
  #   type: file
  #   file-type: stdout
  #   event-processors:
  #     - proc-convert-strings-to-int
  #     - trim-prefixes

processors:
  trim-prefixes:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - path-base:
            apply-on: "name"
  up-down-map:
    event-strings:
      value-names:
        - oper-state
      transforms:
        - replace:
            apply-on: "value"
            old: "up"
            new: "1"
        - replace:
            apply-on: "value"
            old: "down"
            new: "0"
